apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3IuY2xvdWRicmcuY29tIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0Nk1USXpOSEYzWlhKQVN3PT0iCgkJfSwKCQkiaGFyYm9yLmNsb3VkZGFyaS5jb20iOiB7CgkJCSJhdXRoIjogImJXOXZjMjl2YmpFeU5Ub3hNak0wY1hkbGNrQkwiCgkJfSwKCQkiaGFyYm9yLml0cGFydGltZS5jb20iOiB7CgkJCSJhdXRoIjogImJYVnpiMjl1TVRVNk1USXpOSEYzWlhKQVN3PT0iCgkJfQoJfSwKCSJjcmVkSGVscGVycyI6IHsKCQkiYXNpYS5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkiZXUuZ2NyLmlvIjogImdjbG91ZCIsCgkJImdjci5pbyI6ICJnY2xvdWQiLAoJCSJtYXJrZXRwbGFjZS5nY3IuaW8iOiAiZ2Nsb3VkIiwKCQkic3RhZ2luZy1rOHMuZ2NyLmlvIjogImdjbG91ZCIsCgkJInVzLmdjci5pbyI6ICJnY2xvdWQiCgl9Cn0=
kind: Secret
metadata:
  name: harbor-cred
type: kubernetes.io/dockerconfigjson
